# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgReport', '0002_permis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
        migrations.AddField(
            model_name='user',
            name='Permis',
            field=models.ManyToManyField(to='imgReport.Permis'),
        ),
    ]
